"""Backtest engine for QuantForge — ties all backtester components together.

This module exposes:
    - ``BacktestConfig``  — validated Pydantic configuration for a single backtest run.
    - ``BacktestResult``  — structured result model returned after a run completes.
    - ``BacktestEngine``  — orchestrates data ingestion, strategy signal generation,
      and the event-driven MarketEvent → SignalEvent → OrderEvent → FillEvent loop.
"""

from __future__ import annotations

import queue
import uuid
from datetime import date
from typing import Any

from pydantic import BaseModel, Field, model_validator

from quantforge.backtester.events import (
    EventQueue,
    FillEvent,
    MarketEvent,
    OrderEvent,
    SignalEvent,
)
from quantforge.backtester.execution import ExecutionHandler, create_default_execution_handler
from quantforge.backtester.portfolio import PortfolioManager
from quantforge.core import logger
from quantforge.core.exceptions import BacktestError
from quantforge.data.ingestion import DataIngester, data_ingester
from quantforge.data.models import EquityCurvePoint, OHLCVBar, Trade
from quantforge.strategies.base import Signal, SignalType
from quantforge.strategies.registry import strategy_registry


# ── Configuration ──────────────────────────────────────────────────────────────


class BacktestConfig(BaseModel):
    """Validated configuration for a single backtest run.

    Attributes:
        ticker: Asset ticker symbol to backtest (e.g. ``"AAPL"``).
        start: Inclusive start date of the historical period.
        end: Exclusive end date of the historical period. Must be after ``start``.
        interval: yfinance-compatible bar frequency (default ``"1d"``).
        initial_capital: Starting portfolio cash, must be strictly positive.
        strategy_name: Registered name of the strategy to execute.
        strategy_parameters: Keyword arguments forwarded to the strategy constructor.
    """

    ticker: str = Field(..., min_length=1, description="Asset ticker symbol.")
    start: date = Field(..., description="Inclusive backtest start date.")
    end: date = Field(..., description="Exclusive backtest end date.")
    interval: str = Field(default="1d", description="Bar interval (yfinance format).")
    initial_capital: float = Field(
        ..., gt=0, description="Starting portfolio cash (must be > 0)."
    )
    strategy_name: str = Field(
        ..., min_length=1, description="Registered strategy identifier."
    )
    strategy_parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Strategy constructor keyword arguments.",
    )

    @model_validator(mode="after")
    def end_must_be_after_start(self) -> "BacktestConfig":
        """Validates that ``end`` is strictly after ``start``.

        Returns:
            The validated ``BacktestConfig`` instance.

        Raises:
            ValueError: If ``end`` is not strictly after ``start``.
        """
        if self.end <= self.start:
            raise ValueError(
                f"BacktestConfig.end ({self.end}) must be strictly after "
                f"BacktestConfig.start ({self.start})."
            )
        return self


# ── Result ─────────────────────────────────────────────────────────────────────


class BacktestResult(BaseModel):
    """Aggregated result of a completed backtest run.

    Attributes:
        config: The configuration that produced this result.
        trades: All executed trades (from FillEvents) in chronological order.
        equity_curve: Portfolio equity snapshots recorded after each fill.
        final_equity: Portfolio equity at the end of the simulation.
        total_return_pct: Percentage return relative to initial capital.
        total_bars: Number of price bars processed.
        total_signals: Total signals generated by the strategy (all types).
        total_trades: Number of completed trades (fills) executed.
    """

    config: BacktestConfig
    trades: list[Trade]
    equity_curve: list[EquityCurvePoint]
    final_equity: float
    total_return_pct: float
    total_bars: int
    total_signals: int
    total_trades: int


# ── Engine ─────────────────────────────────────────────────────────────────────


class BacktestEngine:
    """Event-driven backtest engine.

    Orchestrates the full backtest pipeline:

    1. Fetch historical OHLCV bars via ``DataIngester``.
    2. Instantiate the requested strategy from the registry.
    3. Pre-generate all signals for the bar series.
    4. Feed ``MarketEvent`` objects into an ``EventQueue``.
    5. Process the queue in a deterministic loop:

       - ``MarketEvent``  → look up pre-generated ``Signal``; if BUY/SELL, emit ``SignalEvent``.
       - ``SignalEvent``  → call ``PortfolioManager.on_signal``; if an ``OrderEvent`` is returned, emit it.
       - ``OrderEvent``   → call ``ExecutionHandler.execute``; emit ``FillEvent``.
       - ``FillEvent``    → call ``PortfolioManager.on_fill``; record the trade.

    6. Build and return a ``BacktestResult``.
    """

    def __init__(
        self,
        execution_handler: ExecutionHandler | None = None,
        data_ingester: DataIngester | None = None,
    ) -> None:
        """Initialises the BacktestEngine with optional dependency overrides.

        Args:
            execution_handler: Custom execution handler; defaults to
                ``create_default_execution_handler()`` (0.1 % slippage + commission).
            data_ingester: Custom data ingester; defaults to the module-level
                ``data_ingester`` singleton from ``quantforge.data.ingestion``.
        """
        self._execution_handler: ExecutionHandler = (
            execution_handler or create_default_execution_handler()
        )
        # Import at module level is fine; the parameter shadows the module import
        # only when an override is provided.
        import quantforge.data.ingestion as _ingestion_mod  # noqa: PLC0415

        self._data_ingester: DataIngester = (
            data_ingester or _ingestion_mod.data_ingester
        )

        logger.debug(
            "BacktestEngine initialised",
            execution_handler=type(self._execution_handler).__name__,
            data_ingester=type(self._data_ingester).__name__,
        )

    # ── Public API ─────────────────────────────────────────────────────────────

    async def run(self, config: BacktestConfig) -> BacktestResult:
        """Executes a full event-driven backtest and returns structured results.

        Args:
            config: Validated ``BacktestConfig`` specifying the run parameters.

        Returns:
            A ``BacktestResult`` with all trades, the equity curve, and summary stats.

        Raises:
            BacktestError: For any fatal backtest-runtime failure (e.g. strategy not found,
                           data fetch failures, or execution inconsistencies).
        """
        logger.info(
            "Backtest starting",
            ticker=config.ticker,
            start=str(config.start),
            end=str(config.end),
            interval=config.interval,
            strategy=config.strategy_name,
            initial_capital=config.initial_capital,
        )

        # ── 1. Fetch historical bars ───────────────────────────────────────────
        bars: list[OHLCVBar] = await self._data_ingester.fetch_historical(
            ticker=config.ticker,
            start=config.start,
            end=config.end,
            interval=config.interval,
        )

        if not bars:
            raise BacktestError(
                message=(
                    f"No price bars returned for ticker '{config.ticker}' "
                    f"({config.start} → {config.end}, interval={config.interval})."
                ),
                ticker=config.ticker,
            )

        logger.debug("Historical bars fetched", bar_count=len(bars))

        # ── 2. Instantiate strategy ────────────────────────────────────────────
        strategy_cls = strategy_registry.get(config.strategy_name)
        strategy = strategy_cls(
            name=config.strategy_name,
            parameters=config.strategy_parameters,
        )

        # ── 3. Pre-generate all signals ────────────────────────────────────────
        signals: list[Signal] = strategy.generate_signals(bars)

        # Build an index keyed by bar position for O(1) lookup in the event loop.
        # The strategy guarantees len(signals) == len(bars) (one signal per bar).
        signal_by_index: dict[int, Signal] = {i: sig for i, sig in enumerate(signals)}

        logger.debug(
            "Signals generated",
            total=len(signals),
            buys=sum(1 for s in signals if s.signal_type == SignalType.BUY),
            sells=sum(1 for s in signals if s.signal_type == SignalType.SELL),
        )

        # ── 4. Initialise stateful components ──────────────────────────────────
        portfolio = PortfolioManager(config.initial_capital)
        event_queue = EventQueue()
        trades: list[Trade] = []

        # Seed the queue — one MarketEvent per bar, in chronological order.
        for bar in bars:
            event_queue.put(MarketEvent(timestamp=bar.timestamp, bar=bar))

        # ── 5. Event processing loop ───────────────────────────────────────────
        current_bar: OHLCVBar | None = None
        bar_index: int = -1  # tracks which MarketEvent we are processing

        while not event_queue.empty():
            try:
                event = event_queue.get()
            except queue.Empty:
                break

            # ── MarketEvent ────────────────────────────────────────────────────
            if isinstance(event, MarketEvent):
                current_bar = event.bar
                bar_index += 1
                current_prices = {current_bar.ticker: current_bar.close}

                signal = signal_by_index.get(bar_index)
                if signal is None:
                    # Defensive: strategy produced fewer signals than bars (warm-up)
                    logger.debug(
                        "No signal for bar index; skipping",
                        bar_index=bar_index,
                    )
                    continue

                if signal.signal_type in (SignalType.BUY, SignalType.SELL):
                    event_queue.put(
                        SignalEvent(
                            timestamp=signal.timestamp,
                            ticker=signal.ticker,
                            signal_type=signal.signal_type,
                            strength=signal.strength,
                            strategy_name=config.strategy_name,
                        )
                    )

            # ── SignalEvent ────────────────────────────────────────────────────
            elif isinstance(event, SignalEvent):
                if current_bar is None:
                    raise BacktestError(
                        message="SignalEvent received before any MarketEvent — invalid state.",
                        ticker=event.ticker,
                    )
                current_prices = {current_bar.ticker: current_bar.close}
                order: OrderEvent | None = portfolio.on_signal(event, current_prices)
                if order is not None:
                    event_queue.put(order)

            # ── OrderEvent ─────────────────────────────────────────────────────
            elif isinstance(event, OrderEvent):
                if current_bar is None:
                    raise BacktestError(
                        message="OrderEvent received before any MarketEvent — invalid state.",
                        ticker=event.ticker,
                    )
                fill: FillEvent = self._execution_handler.execute(event, current_bar)
                event_queue.put(fill)

            # ── FillEvent ──────────────────────────────────────────────────────
            elif isinstance(event, FillEvent):
                if current_bar is None:
                    raise BacktestError(
                        message="FillEvent received before any MarketEvent — invalid state.",
                        ticker=event.ticker,
                    )
                current_prices = {current_bar.ticker: current_bar.close}
                portfolio.on_fill(fill=event, current_prices=current_prices)

                # Record the completed transaction as a Trade domain object.
                trade = Trade(
                    id=str(uuid.uuid4()),
                    ticker=event.ticker,
                    side=event.side,
                    quantity=event.quantity,
                    price=event.fill_price,
                    timestamp=event.timestamp,
                    fees=event.commission + event.slippage,
                )
                trades.append(trade)

            else:
                logger.warning(
                    "Unknown event type encountered; skipping",
                    event_type=type(event).__name__,
                )

        # ── 6. Build result ────────────────────────────────────────────────────
        final_equity = (
            portfolio.cash
            + sum(
                pos.quantity * (bars[-1].close if bars else 0.0)
                for pos in portfolio.positions.values()
            )
        )
        total_return_pct = (
            (final_equity - config.initial_capital) / config.initial_capital * 100.0
        )

        result = BacktestResult(
            config=config,
            trades=trades,
            equity_curve=portfolio.equity_curve,
            final_equity=final_equity,
            total_return_pct=total_return_pct,
            total_bars=len(bars),
            total_signals=len(signals),
            total_trades=len(trades),
        )

        logger.info(
            "Backtest completed",
            ticker=config.ticker,
            total_bars=result.total_bars,
            total_signals=result.total_signals,
            total_trades=result.total_trades,
            final_equity=round(result.final_equity, 4),
            total_return_pct=round(result.total_return_pct, 4),
        )

        return result
