"""Event system driving the event-driven backtesting engine in QuantForge.

This module defines all structural events that flow through the backtester:
MarketEvent -> SignalEvent -> OrderEvent -> FillEvent. All events are implemented
as immutable (frozen) Pydantic v2 models to ensure thread safety and design integrity.
"""

from datetime import datetime
from enum import Enum
import queue
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from quantforge.data.models import OHLCVBar
from quantforge.strategies.base import SignalType


class OrderType(str, Enum):
    """Enumeration representing the execution style of an order."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class MarketEvent(BaseModel):
    """Represents a new price bar (OHLCV) arriving in the backtester.

    This event is triggered by the data handler and consumed by strategies
    to evaluate trading signals.
    """

    model_config = ConfigDict(frozen=True)

    event_type: Literal["MARKET"] = Field(
        default="MARKET",
        description="The type of the event, fixed to 'MARKET'."
    )
    timestamp: datetime = Field(
        ...,
        description="The timestamp when this price bar was registered."
    )
    bar: OHLCVBar = Field(
        ...,
        description="The OHLCV price bar associated with this event."
    )


class SignalEvent(BaseModel):
    """Represents a trading signal generated by a strategy.

    This event is consumed by the portfolio manager to decide whether to
    generate a corresponding OrderEvent.
    """

    model_config = ConfigDict(frozen=True)

    event_type: Literal["SIGNAL"] = Field(
        default="SIGNAL",
        description="The type of the event, fixed to 'SIGNAL'."
    )
    timestamp: datetime = Field(
        ...,
        description="The timestamp when the signal was generated."
    )
    ticker: str = Field(
        ...,
        min_length=1,
        description="The financial instrument ticker symbol."
    )
    signal_type: SignalType = Field(
        ...,
        description="The direction of the signal (BUY, SELL, or HOLD)."
    )
    strength: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalised signal confidence/strength in the range [0.0, 1.0]."
    )
    strategy_name: str = Field(
        ...,
        min_length=1,
        description="The name of the strategy that generated this signal."
    )


class OrderEvent(BaseModel):
    """Represents an order instruction sent from the portfolio manager to the execution handler.

    Validated to ensure correct properties for MARKET and LIMIT order types.
    """

    model_config = ConfigDict(frozen=True)

    event_type: Literal["ORDER"] = Field(
        default="ORDER",
        description="The type of the event, fixed to 'ORDER'."
    )
    timestamp: datetime = Field(
        ...,
        description="The timestamp when the order was generated."
    )
    ticker: str = Field(
        ...,
        min_length=1,
        description="The financial instrument ticker symbol."
    )
    order_type: OrderType = Field(
        ...,
        description="The type of execution order (MARKET or LIMIT)."
    )
    side: Literal["buy", "sell"] = Field(
        ...,
        description="The order side ('buy' or 'sell')."
    )
    quantity: float = Field(
        ...,
        gt=0.0,
        description="The amount/volume of the asset to trade."
    )
    limit_price: float | None = Field(
        default=None,
        description="The worst acceptable price for a LIMIT order. Must be positive if order_type is LIMIT."
    )

    @model_validator(mode="after")
    def validate_limit_price(self) -> "OrderEvent":
        """Ensures that LIMIT orders specify a valid positive limit_price.

        Returns:
            The validated OrderEvent instance.

        Raises:
            ValueError: If a LIMIT order has no limit price or limit price <= 0.
        """
        if self.order_type == OrderType.LIMIT:
            if self.limit_price is None:
                raise ValueError("limit_price must not be None for LIMIT orders.")
            if self.limit_price <= 0:
                raise ValueError(f"limit_price must be greater than 0, got {self.limit_price}.")
        return self


class FillEvent(BaseModel):
    """Represents an executed order (a transaction) generated by the execution handler.

    Triggers updating portfolio holdings, cash balances, and equity metrics.
    """

    model_config = ConfigDict(frozen=True)

    event_type: Literal["FILL"] = Field(
        default="FILL",
        description="The type of the event, fixed to 'FILL'."
    )
    timestamp: datetime = Field(
        ...,
        description="The timestamp when the order was filled."
    )
    ticker: str = Field(
        ...,
        min_length=1,
        description="The financial instrument ticker symbol."
    )
    side: Literal["buy", "sell"] = Field(
        ...,
        description="The fill side ('buy' or 'sell')."
    )
    quantity: float = Field(
        ...,
        gt=0.0,
        description="The executed amount/volume."
    )
    fill_price: float = Field(
        ...,
        gt=0.0,
        description="The execution price per unit."
    )
    commission: float = Field(
        default=0.0,
        ge=0.0,
        description="The transaction fee overhead charged."
    )
    slippage: float = Field(
        default=0.0,
        ge=0.0,
        description="The execution slippage overhead incurred."
    )

    @property
    def total_cost(self) -> float:
        """Calculates total net cash impact (cost) of the completed trade.

        For buys, includes transaction overheads (+ commission + slippage).
        For sells, subtracts transaction overheads (- commission - slippage).

        Returns:
            The total net cash cost (positive for cash outflow, negative or positive depending on side).
        """
        base_value = self.quantity * self.fill_price
        if self.side == "buy":
            return base_value + self.commission + self.slippage
        else:
            return base_value - self.commission - self.slippage


# Union Type Alias representing any valid backtester event.
BacktestEvent = MarketEvent | SignalEvent | OrderEvent | FillEvent


class EventQueue:
    """Synchronous FIFO event queue that acts as the messaging backbone of the backtester.

    This thin wrapper around standard library's `queue.Queue` facilitates a single-threaded,
    fully deterministic execution flow.
    """

    def __init__(self) -> None:
        """Initialises the event queue."""
        self._queue: queue.Queue[BacktestEvent] = queue.Queue()

    def put(self, event: BacktestEvent) -> None:
        """Puts a new backtesting event onto the queue.

        Args:
            event: The backtester event to add.
        """
        self._queue.put(event)

    def get(self) -> BacktestEvent:
        """Gets and removes the next backtesting event from the queue.

        This method is non-blocking to prevent thread deadlocks in case of logical bugs.

        Returns:
            The next BacktestEvent.

        Raises:
            queue.Empty: If the queue is empty.
        """
        return self._queue.get_nowait()

    def empty(self) -> bool:
        """Checks whether the event queue is currently empty.

        Returns:
            True if there are no events in the queue, False otherwise.
        """
        return self._queue.empty()

    def size(self) -> int:
        """Returns the current number of events pending in the queue.

        Returns:
            The size of the queue.
        """
        return self._queue.qsize()
